set -g @plugin 'tmux-plugins/tmux-cpu'
set -g allow-passthrough on
set -g status-interval 5
set -g status-right "#[fg=#40a02b]󰻠 #{cpu_percentage} #[fg=colour179]󰍛 #{ram_percentage} #[fg=colour97] #(smctemp -c 2>/dev/null) #[fg=colour24] #h"
