if-shell 'test -x "$HOME/.local/opt/dev-tools/bin/zsh"' 'set -g default-shell "$HOME/.local/opt/dev-tools/bin/zsh"'

set -g allow-passthrough off
set -g status-interval 30
set -g status-right "#[fg=colour24] #h #[fg=#5c5f77]%H:%M"
